cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

shop/api/urls.py
from django.urls import path,include
from shop.api import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('shop', views.CategoryViewSet)
router.register('shop/', views.ProductViewSet)
router.register('users', views.UserViewSet)
router.register('Group', views.GroupViewSet)


urlpatterns = [
    path('',include(router.urls))
]

shop/urls.py
from django.conf.urls import url
from shop import views
from django.urls import path
app_name = 'shop'

urlpatterns = [
    path('search/',views.SearchRView, name='search_results'),
    path('', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),

]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

shop/forms.py
from django import forms
from django.contrib.auth.models import User

class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter password'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter password again'}))

    class Meta:
        model = User
        fields = {
            'username',
            'first_name',
            'last_name',
            'email',
        }

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError("Password Mismatch")
        return confirm_password


# contact form
class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    content = forms.CharField(required=True)

shop/api/views.py
from shop.models import Category,Product
from shop.api.serializers import CategorySerializer,ProductSerializer,UserSerializer,GroupSerializer
from django.contrib.auth.models import User, Group
from rest_framework import viewsets

from shop.pagination import MyPagination

from rest_framework.permissions import IsAuthenticated,IsAdminUser

from rest_framework_jwt.authentication import JSONWebTokenAuthentication

# Create your views here.

class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    pagination_class = MyPagination

    permission_classes = (IsAuthenticated,IsAdminUser,)
    authentication_classes = (JSONWebTokenAuthentication,)




class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer
    pagination_class = MyPagination

    permission_classes = (IsAuthenticated,IsAdminUser,)
    authentication_classes = (JSONWebTokenAuthentication,)

class CategoryViewSet(viewsets.ModelViewSet):
    queryset =Category.objects.all()
    serializer_class =CategorySerializer
    pagination_class = MyPagination

    permission_classes = (IsAuthenticated,IsAdminUser,)
    authentication_classes = (JSONWebTokenAuthentication,)

class ProductViewSet(viewsets.ModelViewSet):
    queryset =Product.objects.all()
    serializer_class =ProductSerializer
    pagination_class = MyPagination

    permission_classes = (IsAuthenticated,IsAdminUser,)
    authentication_classes = (JSONWebTokenAuthentication,)

shop/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.db.models import Q  # 3new
from shop.forms import ContactForm,UserRegisterForm

from django.core.paginator import InvalidPage, Paginator
from django.http import Http404


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    paginator = Paginator(products,16)
    is_paginated = True if paginator.num_pages > 1 else False
    page = request.GET.get('page') or 1
    try:
        current_page = paginator.page(page)
    except InvalidPage as e:
        raise Http404(str(e))

    context = {
        'category': category,
        'categories': categories,
        'products': products,
        'current_page': current_page,
        'is_paginated': is_paginated,
    }


    return render(request, 'shop/product/list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()

    context = {
        'product': product,
        'cart_product_form': cart_product_form

    }



    return render(request, 'shop/product/detail.html', context)

def SearchRView(request):
    if not None:
        query = request.GET.get('q')
        pr = Product.objects.filter(Q(name__icontains=query) | Q(name__istartswith=query)| Q(name__endswith=query) | Q(name__istartswith=query)| Q(category__name__icontains=query)| Q(category__name__startswith=query)|Q(price__exact=query) | Q(image__icontains=query))
        # cr=Category.objects.filter(Q(name__icontains=query)|Q(name__iexact=query))


        return render(request, 'search/search_results.html', {'pr': pr})
    else:
        return redirect(product_detail)


# from django.shortcuts import render, redirect, HttpResponse, get_object_or_404, HttpResponseRedirect
# from django.contrib.auth.forms import UserCreationForm
# from shop.form import u
from django.core.mail import EmailMessage
from django.template.loader import get_template

# from django.contrib.auth.models import User, Group
# from rest_framework import viewsets
# from .serializers import *

#
# # Create your views here.
#
# class UserViewSet(viewsets.ModelViewSet):
#     """
#     API endpoint that allows users to be viewed or edited.
#     """
#     queryset = User.objects.all().order_by('-date_joined')
#     serializer_class = UserSerializer
#
#
# class GroupViewSet(viewsets.ModelViewSet):
#     """
#     API endpoint that allows groups to be viewed or edited.
#     """
#     queryset = Group.objects.all()
#     serializer_class = GroupSerializer


# redirect success page
def Success(request):
    return render(request, 'blog/success.html')


# sign up form
def SignUp(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return redirect(Success)
    else:
        form = UserRegisterForm()
    return render(request, "registration/signup.html", {'form': form})


# Contact form view

def Contact(request):
    Contact_Form = ContactForm
    if request.method == 'POST':
        form = Contact_Form(data=request.POST)

        if form.is_valid():
            contact_name = request.POST.get('contact_name')
            contact_email = request.POST.get('contact_email')
            contact_content = request.POST.get('content')

            template = get_template('blog/contact_form.txt')
            context = {
                'contact_name': contact_name,
                'contact_email': contact_email,
                'contact_content': contact_content,
            }

            content = template.render(context)

            email = EmailMessage(
                "New contact form email",
                content,
                "Creative web" + '',
                ['myfriendkhendelwal@gmail.com'],
                headers={'Reply To': contact_email}
            )

            email.send()

            return redirect('blog:success')
    return render(request, 'blog/contact.html', {'form': Contact_Form})

templates/shop/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}On-line Shop{% endblock %}</title>
	<meta name="description" content=" Divisima | eCommerce Template">
	<meta name="keywords" content="divisima, eCommerce, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- account -->
<!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
      <!--Import materialize.css-->
{% block loginrg %}
{% endblock %}
{#      <link rel="stylesheet" href="/static/blog/materialize/css/materialize.min.css"/>#}
<!-- Favicon -->
	<link href="{% static "home/img/favicon.ico" %}" rel="shortcut icon"/>

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,300i,400,400i,700,700i" rel="stylesheet">


	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static "home/css/bootstrap.min.css" %}"/>
	<link rel="stylesheet" href="{% static "home/css/font-awesome.min.css" %}"/>
	<link rel="stylesheet" href="{% static "home/css/flaticon.css" %}"/>
	<link rel="stylesheet" href="{% static "home/css/slicknav.min.css" %}"/>
	<link rel="stylesheet" href="{% static "home/css/jquery-ui.min.css" %}"/>
	<link rel="stylesheet" href="{% static "home/css/owl.carousel.min.css" %}"/>
	<link rel="stylesheet" href="{% static "home/css/animate.css" %}"/>
	<link rel="stylesheet" href="{% static "home/css/style.css" %}"/>


	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
<style>
  input[type=email]{
      width: 100%;
      padding: 12px 20px;
      margin: 8px 0;
      display: inline-block;
      border:1px solid #ccc;
      border-radius: 25px;
      box-sizing: border-box;
  }
     input[type=number]{
      width: 100%;
      padding: 12px 20px;
      margin: 8px 0;
      display: inline-block;
      border:1px solid #ccc;
      border-radius: 25px;
      box-sizing: border-box;
  }
    </style>


</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
	<header class="header-section">
		<div class="header-top">
			<div class="container">
				<div class="row">
					<div class="col-lg-2 text-center text-lg-left">
						<!-- logo -->
						<a href="/shop/" class="site-logo">
							<img src="{% static "home/img/logo.jpg" %}" alt="">
						</a>
					</div>
					<div class="col-xl-6 col-lg-5">
						<form class="header-search-form" action="/shop/search/" method="get">
							<input name="q" type="text" placeholder="Search on Products only in Onlineshoping....">
							<button><i class="flaticon-search"></i></button>
						</form>
					</div>
					<div class="col-xl-4 col-lg-5">
						<div class="user-panel">
							<div class="up-item">
								<i class="flaticon-profile"></i>
								<a href="/accounts/login/">login</a> In or <a href="/signup/">Create Account</a>


							</div>
                              {% with totail_items=cart|length %}
                                        {% if cart|length > 0 %}
                                            <a href="{% url "cart:cart_detail" %}" style="color: #ffffff"> </a>
							            <div class="up-item">
								                <div class="shopping-card">
									                <i class="flaticon-bag"></i>
									                    <span>{{ totail_items }} item {{ totail_items|pluralize }}</span>
								                </div>
								            <a href="#">Shopping Cart</a>

{#                                                , Kshs. {{ cart.get_total_price }}#}

                                        {% else %}
                                            Your cart is empty.
                                    {% endif %}
                                  {% endwith %}

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<nav class="main-navbar">
			<div class="container">
				<!-- menu -->
				<ul class="main-menu">
					<li><a href="/shop/">Home</a></li>
{#					<li><a href="#">Women</a></li>#}
{#					<li><a href="#">Men</a></li>#}
{#					<li><a href="#">Jewelry#}
{#						<span class="new">New</span>#}
{#					</a></li>#}
{#					<li><a href="#">Shoes</a>#}
{#						<ul class="sub-menu">#}
{#							<li><a href="#">Sneakers</a></li>#}
{#							<li><a href="#">Sandals</a></li>#}
{#							<li><a href="#">Formal Shoes</a></li>#}
{#							<li><a href="#">Boots</a></li>#}
{#							<li><a href="#">Flip Flops</a></li>#}
{#						</ul>#}
{#					</li>#}
{#					<li><a href="#">Pages</a>#}
{#						<ul class="sub-menu">#}
{#							<li><a href="./product.html">Product Page</a></li>#}
{#							<li><a href="./category.html">Category Page</a></li>#}
{#							<li><a href="./cart.html">Cart Page</a></li>#}
{#							<li><a href="./checkout.html">Checkout Page</a></li>#}
{#							<li><a href="./contact.html">Contact Page</a></li>#}
{#						</ul>#}
{#					</li>#}
                    <li> {% if user.is_authenticated %}
                            <li><a href="#">{{ user.username }}</a></li>
                            <li><a href="{% url 'logout' %}">Log Out</a></li>
                            <li><a href="{% url 'password_change' %}">Change Password</a></li>
                            {% else %}
                        <li><a href="{% url 'signup' %}">Sign Up</a></li>
                        <li><a href="{% url 'login' %}">Log In</a></li>
                        {% endif %}
                    </li>
{#					<li><a href="/blog/">Blog</a></li>#}
				</ul>
			</div>
		</nav>
	</header>
	<!-- Header section end -->


{% block baner %}
{% endblock %}
<div class="container">
    <div class="row" style="margin-top: 6%">
         <button class="btn btn-info pull-right">
            {% with totail_items=cart|length %}
                {% if cart|length > 0 %}
                    My Shopping Order:
                    <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">

                        {{ totail_items }} item {{ totail_items|pluralize }}, Kshs. {{ cart.get_total_price }}
                    </a>
                    {% else %}
                    Your cart is empty.
                {% endif %}
            {% endwith %}
         </button>
    </div>
</div>
{% block content %}


{% endblock %}
{##}

	<!-- Footer section -->
	<section class="footer-section">
		<div class="container">
			<div class="footer-logo text-center">
				<a href="index.html"><img src="{% static "home/img/LOGO1.svg" %}" alt="" style="height: 200px"width="300px"></a>
			</div>
			<div class="row">
				<div class="col-lg-3 col-sm-6">
					<div class="footer-widget about-widget">
						<h2>About</h2>
						<p>Donec vitae purus nunc. Morbi faucibus erat sit amet congue mattis. Nullam frin-gilla faucibus urna, id dapibus erat iaculis ut. Integer ac sem.</p>
						<img src="{% static "home/img/cards.png" %}" alt="">
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="footer-widget about-widget">
{#						<h2>Questions</h2>#}
{#						<ul>#}
{#							<li><a href="">About Us</a></li>#}
{#							<li><a href="">Track Orders</a></li>#}
{#							<li><a href="">Returns</a></li>#}
{#							<li><a href="">Jobs</a></li>#}
{#							<li><a href="">Shipping</a></li>#}
{#							<li><a href="">Blog</a></li>#}
{#						</ul>#}
{#						<ul>#}
{#							<li><a href="">Partners</a></li>#}
{#							<li><a href="">Bloggers</a></li>#}
{#							<li><a href="">Support</a></li>#}
{#							<li><a href="">Terms of Use</a></li>#}
{#							<li><a href="">Press</a></li>#}
{#						</ul>#}
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="footer-widget about-widget">
						<h2>Questions</h2>
						<div class="fw-latest-post-widget">
							<div class="lp-item">
								<div class="lp-thumb set-bg" data-setbg="{% static "home/img/blog-thumbs/image2.jpg" %}"></div>
								<div class="lp-content">
									<h6>what shoes to wear</h6>
									<span>Oct 21, 2018</span>
									<a href="#" class="readmore">Read More</a>
								</div>
							</div>
							<div class="lp-item">
								<div class="lp-thumb set-bg" data-setbg="{% static "home/img/blog-thumbs/product-thumb-4.jpg" %}"></div>
								<div class="lp-content">
									<h6>trends this year</h6>
									<span>Oct 21, 2018</span>
									<a href="#" class="readmore">Read More</a>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="footer-widget contact-widget">
						<h2>Questions</h2>
						<div class="con-info">
							<span>C.</span>
							<p>Your Company Ltd </p>
						</div>
						<div class="con-info">
							<span>B.</span>
							<p>company address</p>
						</div>
						<div class="con-info">
							<span>T.</span>
							<p>+53 345 7953 32453</p>
						</div>
						<div class="con-info">
							<span>E.</span>
							<p>office@youremail.com</p>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="social-links-warp">
			<div class="container">
				<div class="social-links">
					<a href="" class="instagram"><i class="fa fa-instagram"></i><span>instagram</span></a>
					<a href="" class="google-plus"><i class="fa fa-google-plus"></i><span>g+plus</span></a>
					<a href="" class="pinterest"><i class="fa fa-pinterest"></i><span>pinterest</span></a>
					<a href="" class="facebook"><i class="fa fa-facebook"></i><span>facebook</span></a>
					<a href="" class="twitter"><i class="fa fa-twitter"></i><span>twitter</span></a>
					<a href="" class="youtube"><i class="fa fa-youtube"></i><span>youtube</span></a>
					<a href="" class="tumblr"><i class="fa fa-tumblr-square"></i><span>tumblr</span></a>
				</div>



<p class="text-white text-center mt-5">Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This django ,  python is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by Mohan</a></p>


			</div>
		</div>
	</section>
	<!-- Footer section end -->



	<!--====== Javascripts & Jquery ======-->
	<script src="{% static "home/js/jquery-3.2.1.min.js" %}"></script>
	<script src="{% static "home/js/bootstrap.min.js" %}"></script>
	<script src="{% static "home/js/jquery.slicknav.min.js" %}"></script>
	<script src="{% static "home/js/owl.carousel.min.js" %}"></script>
	<script src="{% static "home/js/jquery.nicescroll.min.js" %}"></script>
	<script src="{% static "home/js/jquery.zoom.min.js" %}"></script>
	<script src="{% static "home/js/jquery-ui.min.js" %}"></script>
	<script src="{% static "home/js/main.js" %}"></script>

	</body>
</html>

templates/shop/navbar.html
{% load static %}
{#<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0px; background-color: #5AC8FA;">#}
{#  <!-- Brand and toggle get grouped for better mobile display -->#}
{#  <div class="container-fluid">#}
{#      <div class="navbar-header">#}
{#    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">#}
{#      <span class="sr-only">Toggle navigation</span>#}
{#      <span class="icon-bar"></span>#}
{#      <span class="icon-bar"></span>#}
{#      <span class="icon-bar"></span>#}
{#    </button>#}
{#    <a class="navbar-brand" href="{% url 'shop:product_list' %}" style="color: #ffffff">Onlineshop</a>#}
{#  </div>#}
{##}
{#  <!-- Collect the nav links, forms, and other content for toggling -->#}
{#  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">#}
{##}
{#    <ul class="nav navbar-nav navbar-right">#}
{#      <li class="dropdown">#}
{#          {% if request.user.is_authenticated %}#}
{#        <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: #ffffff">{{ request.user.username }}<b class="caret"></b></a>#}
{#        <ul class="dropdown-menu">#}
{#          <li><a href="">logout</a></li>#}
{#            {% else %}#}
{#          <li class="divider"></li>#}
{#          <li><a href="#" style="color: #ffffff">Sign in</a></li>#}
{#         <li><a href="#" style="color: #ffffff">Sign up</a></li>#}
{#        </ul>#}
{#         {% endif %}#}
{#      </li>#}
{#    </ul>#}
{#  </div><!-- /.navbar-collapse -->#}
{#  </div>#}
{#</nav>#}

	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
	<header class="header-section">
		<div class="header-top">
			<div class="container">
				<div class="row">
					<div class="col-lg-2 text-center text-lg-left">
						<!-- logo -->
						<a href="./index.html" class="site-logo">
							<img src="{% static "home/img/logo.png" %}" alt="">
						</a>
					</div>
					<div class="col-xl-6 col-lg-5">
						<form class="header-search-form" action="/shop/search/" method="get">
							<input name="q" type="text" placeholder="Search on divisima ....">
							<button><i class="flaticon-search"></i></button>
						</form>
					</div>
					<div class="col-xl-4 col-lg-5">
						<div class="user-panel">
							<div class="up-item">
								<i class="flaticon-profile"></i>
								<a href="/accounts/login/">login</a> In or <a href="/shop/signup/">Create Account</a>


							</div>
                              {% with totail_items=cart|length %}
                                        {% if cart|length > 0 %}
                                            <a href="{% url "cart:cart_detail" %}" style="color: #ffffff"> </a>
							            <div class="up-item">
								                <div class="shopping-card">
									                <i class="flaticon-bag"></i>
									                    <span>{{ totail_items }} item {{ totail_items|pluralize }}</span>
								                </div>
								            <a href="#">Shopping Cart</a>

{#                                                , Kshs. {{ cart.get_total_price }}#}

                                        {% else %}
                                            Your cart is empty.
                                    {% endif %}
                                  {% endwith %}

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<nav class="main-navbar">
			<div class="container">
				<!-- menu -->
				<ul class="main-menu">
					<li><a href="#">Home</a></li>
{#					<li><a href="#">Women</a></li>#}
{#					<li><a href="#">Men</a></li>#}
{#					<li><a href="#">Jewelry#}
{#						<span class="new">New</span>#}
{#					</a></li>#}
{#					<li><a href="#">Shoes</a>#}
{#						<ul class="sub-menu">#}
{#							<li><a href="#">Sneakers</a></li>#}
{#							<li><a href="#">Sandals</a></li>#}
{#							<li><a href="#">Formal Shoes</a></li>#}
{#							<li><a href="#">Boots</a></li>#}
{#							<li><a href="#">Flip Flops</a></li>#}
{#						</ul>#}
{#					</li>#}
{#					<li><a href="#">Pages</a>#}
{#						<ul class="sub-menu">#}
{#							<li><a href="./product.html">Product Page</a></li>#}
{#							<li><a href="./category.html">Category Page</a></li>#}
{#							<li><a href="./cart.html">Cart Page</a></li>#}
{#							<li><a href="./checkout.html">Checkout Page</a></li>#}
{#							<li><a href="./contact.html">Contact Page</a></li>#}
{#						</ul>#}
{#					</li>#}
                    <li> {% if user.is_authenticated %}
                            <li><a href="#">{{ user.username }}</a></li>
                            <li><a href="{% url 'logout' %}">Log Out</a></li>
                            <li><a href="{% url 'password_change' %}">Change Password</a></li>
                            {% else %}
                        <li><a href="{% url 'blog:signup' %}">Sign Up</a></li>
                        <li><a href="{% url 'login' %}">Log In</a></li>
                        {% endif %}
                    </li>
					<li><a href="/blog/">Blog</a></li>
				</ul>
			</div>
		</nav>
	</header>
	<!-- Header section end -->